Farsyte::Matrix::Matrix< Nc, Nr, T >
NAME
Farsyte::Matrix::Matrix< Nc, Nr, T > -
Matrix Template.
SYNOPSIS
#include <matrix_matrix.hh>
Public Types
typedef std::array< T, Nr *Nc > A
Typedef for array containing the data.
Public Member Functions
Matrix ()
Matrix Default Constructor.
Matrix (T const &d)
Matrix Diagonal Constructor.
Matrix (A const &iv)
Matrix Construction from Array of Arrays.
Matrix (Matrix const &m)
Duplicate Matrix Construction.
T const & operator[] (int i) const
Fast linear element access (read-only).
T & operator[] (int i)
Fast linear element access (mutable).
T const & operator() (int ri, int ci=0) const
Matrix Subscripting Operator.
T & operator() (int ri, int ci=0)
Matrix Subscripting Operator.
bool equals (Matrix const &p) const
Matrix Equality Test.
Matrix & increment_by (Matrix const &p)
Matrix Increment operation.
Matrix & operator+= (Matrix const &p)
Matrix Increment operator.
Matrix & decrement_by (Matrix const &p)
Matrix Decrement operation.
Matrix & operator-= (Matrix const &p)
Matrix Decrement operator.
Matrix & scalar_mul_by (T const &p)
Matrix Scalar Multiply operation.
Matrix & operator*= (T const &p)
Matrix Scalar Multiply operator.
Matrix & scalar_div_by (T const &p)
Matrix Scalar Divide operation.
Matrix & operator/= (T const &p)
Matrix Scalar Divide operator.
Matrix negate ()
Matrix Negate operation.
Matrix< Nr, Nc, T > transpose () const
Matrix Transpose operation.
Static Public Member Functions
static int rows ()
Matrix rows.
static int cols ()
Matrix columns.
static int size ()
Matrix elements.
Protected Member Functions
int off (int ri, int ci) const
Matrix subscript to offset calculation.
T const & data (int ri, int ci=0) const
Matrix Subscripting Implementation.
T & data (int ri, int ci=0)
Matrix Subscripting Implementation.
Protected Attributes
A a
Storage for Matrix State.
Detailed Description
template<int Nc, int Nr, typename T>class Farsyte::Matrix::Matrix< Nc, Nr, T >
Matrix Template.
Parameters:
Nc Number of columns in the matrix.
Nr Number of rows in the matrix.
T Data type for each matrix element.
This template implements rectangular matrices of a compile-time determined size, containing elements of compile-time determined type.
Definition at line 31 of file matrix_matrix.hh.
Constructor & Destructor Documentation
template<int Nc, int Nr, typename T> Farsyte::Matrix::Matrix< Nc, Nr, T >::Matrix () [inline]
Matrix Default Constructor. Matrix objects that are default-constructed are assured of having each element appropriately initialized.
Definition at line 97 of file matrix_matrix.hh.
                    : a() {
            }
template<int Nc, int Nr, typename T> Farsyte::Matrix::Matrix< Nc, Nr, T >::Matrix (T const &d) [inline]
Matrix Diagonal Constructor.
Parameters:
d Value to copy into each diagonal element.
Definition at line 104 of file matrix_matrix.hh.
                    : a() {
                for (int i = 0; (i < Nr) && (i < Nc); ++i)
                    data(i, i) = d;
            }
template<int Nc, int Nr, typename T> Farsyte::Matrix::Matrix< Nc, Nr, T >::Matrix (A const &iv) [inline]
Matrix Construction from Array of Arrays.
Parameters:
iv initialization vector. This method is used by subclasses to provide value construction of Matrices using appropriately sized and shaped initialization vectors.
Note:
Not a public interface: only classes within the class heirarchy below Matrix should be aware of the data organization within the Matrix object.
Definition at line 119 of file matrix_matrix.hh.
                    : a(iv) {
            }
template<int Nc, int Nr, typename T> Farsyte::Matrix::Matrix< Nc, Nr, T >::Matrix (Matrix< Nc, Nr, T > const &m) [inline]
Duplicate Matrix Construction.
Parameters:
m Matrix to duplicate. Initialize this matrix to duplicate the data contained in the provided matrix.
Definition at line 128 of file matrix_matrix.hh.
                    : a(m.a) {
            }
Member Function Documentation
template<int Nc, int Nr, typename T> static int Farsyte::Matrix::Matrix< Nc, Nr, T >::cols () [inline], [static]
Matrix columns.
Returns:
number of columns Nc in tha matrix.
Definition at line 48 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::size().
                              {
                return Nc;
            }
template<int Nc, int Nr, typename T> T const& Farsyte::Matrix::Matrix< Nc, Nr, T >::data (intri, intci = 0) const [inline], [protected]
Matrix Subscripting Implementation.
Parameters:
ri Row Index, ranging from 1 to Nr inclusive.
ci Column Index, ranging from 1 to Nc inclusive.
Returns:
a read-only reference to the selected element.
Note:
Fortran conventions for array subscripting.
Definition at line 77 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::decrement_by(), Farsyte::Matrix::Matrix< 1, Nr, double >::equals(), Farsyte::Matrix::Matrix< 1, Nr, double >::increment_by(), Farsyte::Matrix::Matrix< 1, Nr, double >::Matrix(), Farsyte::Matrix::Matrix< 1, Nr, double >::negate(), Farsyte::Matrix::Matrix< 1, Nr, double >::operator()(), Farsyte::Matrix::Matrix< 1, Nr, double >::scalar_div_by(), Farsyte::Matrix::Matrix< 1, Nr, double >::scalar_mul_by(), and Farsyte::Matrix::Matrix< 1, Nr, double >::transpose().
                                                    {
                return a[off(ri, ci)];
            }
template<int Nc, int Nr, typename T> T& Farsyte::Matrix::Matrix< Nc, Nr, T >::data (intri, intci = 0) [inline], [protected]
Matrix Subscripting Implementation.
Parameters:
ri Row Index, ranging from 1 to Nr inclusive.
ci Column Index, ranging from 1 to Nc inclusive.
Returns:
a writable reference to the selected element.
Note:
Fortran conventions for array subscripting.
Definition at line 87 of file matrix_matrix.hh.
                                        {
                return a[off(ri, ci)];
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::decrement_by (Matrix< Nc, Nr, T > const &p) [inline]
Matrix Decrement operation.
Parameters:
p Matrix of decrement values.
Returns:
this matrix, after decrementing. Each element of this matrix is decremented by the value of the corresponding element of the provided matrix.
Definition at line 212 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::operator-=().
                                                  {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        data(ri, ci) -= p.data(ri, ci);
                return *this;
            }
template<int Nc, int Nr, typename T> bool Farsyte::Matrix::Matrix< Nc, Nr, T >::equals (Matrix< Nc, Nr, T > const &p) const [inline]
Matrix Equality Test.
Parameters:
p Matrix to compare.
Returns:
true if all elements compare equal, else false.
Definition at line 172 of file matrix_matrix.hh.
                                               {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        if (data(ri, ci) != p.data(ri, ci))
                            return false;
                return true;
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::increment_by (Matrix< Nc, Nr, T > const &p) [inline]
Matrix Increment operation.
Parameters:
p Matrix of increment values.
Returns:
this matrix, after incrementing. Each element of this matrix is incremented by the value of the corresponding element of the provided matrix.
Definition at line 187 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::operator+=().
                                                  {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        data(ri, ci) += p.data(ri, ci);
                return *this;
            }
template<int Nc, int Nr, typename T> Matrix Farsyte::Matrix::Matrix< Nc, Nr, T >::negate () [inline]
Matrix Negate operation.
Returns:
self after negating elements.
Definition at line 279 of file matrix_matrix.hh.
                            {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        data(ri, ci) = -data(ri, ci);
                return *this;
            }
template<int Nc, int Nr, typename T> T const& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator() (intri, intci = 0) const [inline]
Matrix Subscripting Operator.
Parameters:
ri Row Index, in the range 1 to Nr inclusive.
ci Column Index, in the range 1 to Nc inclusive.
Returns:
read-only reference to the selected element.
Note:
Fortran conventions for array subscripting.
Definition at line 154 of file matrix_matrix.hh.
                                                          {
                return data(ri, ci);
            }
template<int Nc, int Nr, typename T> T& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator() (intri, intci = 0) [inline]
Matrix Subscripting Operator.
Parameters:
ri Row Index, in the range 1 to Nr inclusive.
ci Column Index, in the range 1 to Nc inclusive.
Returns:
modifiable reference to the selected element.
Note:
Fortran conventions for array subscripting.
Definition at line 164 of file matrix_matrix.hh.
                                              {
                return data(ri, ci);
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator*= (T const &p) [inline]
Matrix Scalar Multiply operator.
Parameters:
p Scalaing Factor.
Returns:
this matrix, after scaling values up. Each element of this matrix is multiplied by the provided scale factor.
Definition at line 249 of file matrix_matrix.hh.
                                           {
                return scalar_mul_by(p);
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator+= (Matrix< Nc, Nr, T > const &p) [inline]
Matrix Increment operator.
Parameters:
p Matrix of increment values.
Returns:
this matrix, after incrementing. Each element of this matrix is incremented by the value of the corresponding element of the provided matrix.
Definition at line 201 of file matrix_matrix.hh.
                                                {
                return increment_by(p);
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator-= (Matrix< Nc, Nr, T > const &p) [inline]
Matrix Decrement operator.
Parameters:
p Matrix of decrement values.
Returns:
this matrix, after decrementing. Each element of this matrix is decremented by the value of the corresponding element of the provided matrix.
Definition at line 226 of file matrix_matrix.hh.
                                                {
                return decrement_by(p);
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator/= (T const &p) [inline]
Matrix Scalar Divide operator.
Parameters:
p Scaling Factor.
Returns:
this matrix, after scaling values down. Each element of this matrix is divided by the scaling factor.
Definition at line 272 of file matrix_matrix.hh.
                                           {
                return scalar_div_by(p);
            }
template<int Nc, int Nr, typename T> T const& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator[] (inti) const [inline]
Fast linear element access (read-only).
Parameters:
i element index.
Returns:
an element within the matrix.
Definition at line 136 of file matrix_matrix.hh.
                                             {
                return a[i];
            }
template<int Nc, int Nr, typename T> T& Farsyte::Matrix::Matrix< Nc, Nr, T >::operator[] (inti) [inline]
Fast linear element access (mutable).
Parameters:
i element index.
Returns:
an element within the matrix.
Definition at line 144 of file matrix_matrix.hh.
                                 {
                return a[i];
            }
template<int Nc, int Nr, typename T> static int Farsyte::Matrix::Matrix< Nc, Nr, T >::rows () [inline], [static]
Matrix rows.
Returns:
number of rows Nr in tha matrix.
Definition at line 41 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::size().
                              {
                return Nr;
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::scalar_div_by (T const &p) [inline]
Matrix Scalar Divide operation.
Parameters:
p Scaling Factor.
Returns:
this matrix, after scaling values down. Each element of this matrix is divided by the scaling factor.
Definition at line 259 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::operator/=().
                                              {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        data(ri, ci) /= p;
                return *this;
            }
template<int Nc, int Nr, typename T> Matrix& Farsyte::Matrix::Matrix< Nc, Nr, T >::scalar_mul_by (T const &p) [inline]
Matrix Scalar Multiply operation.
Parameters:
p Scaling factor.
Returns:
this matrix, after scaling values up. Each element of this matrix is multiplied by the provided scale factor.
Definition at line 236 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::operator*=().
                                              {
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        data(ri, ci) *= p;
                return *this;
            }
template<int Nc, int Nr, typename T> static int Farsyte::Matrix::Matrix< Nc, Nr, T >::size () [inline], [static]
Matrix elements.
Returns:
number of elements Nr*Nc in the matrix.
Definition at line 55 of file matrix_matrix.hh.
                              {
                return rows() * cols();
            }
template<int Nc, int Nr, typename T> Matrix<Nr, Nc, T> Farsyte::Matrix::Matrix< Nc, Nr, T >::transpose () const [inline]
Matrix Transpose operation.
Returns:
transposed matrix.
Definition at line 290 of file matrix_matrix.hh.
                              {
                Matrix<Nr, Nc, T> R;
                for (int ci = 0; ci < Nc; ++ci)
                    for (int ri = 0; ri < Nr; ++ri)
                        R(ci, ri) = data(ri, ci);
                return R;
            }
Member Data Documentation
template<int Nc, int Nr, typename T> A Farsyte::Matrix::Matrix< Nc, Nr, T >::a [protected]
Storage for Matrix State.
Definition at line 300 of file matrix_matrix.hh.
Referenced by Farsyte::Matrix::Matrix< 1, Nr, double >::data(), and Farsyte::Matrix::Matrix< 1, Nr, double >::operator[]().
Author
Generated automatically by Doxygen for The Farsyte Toolkit from the source code.