Farsyte::Testing::Test
NAME
Farsyte::Testing::Test -
The Test object.
SYNOPSIS
#include <testing_test.hh>
Public Member Functions
std::string drain ()
Get (and clear) accumulated output.
template<typename T > Test & operator<< (T const &t)
Append output text.
Test & operator<< (std::ostream &(*man)(std::ostream &stream))
Apply I/O manipulator.
Test (Suite &ref, std::string const &name)
Construct a new Test object.
void fail (std::string const &cond)
Register a Test FAIL.
void skip (std::string const &cond)
Register a Test SKIP.
void error (std::string const &cond)
Register a Test ERROR.
void pass (std::string const &cond)
Register a Test PASS.
~Test ()
Suite Destructor.
int check (bool ok, std::string const &msg) __attribute__((unused))
Support code for logging a condition check result.
template<typename T , typename U > int check_op (T const &ov, U const &ev, bool ok, std::string const &op, std::string const &msg) __attribute__((unused))
Support Template for performing a condition test.
template<typename T > int check_op (T const &ov, T const &ev, bool ok, std::string const &op, std::string const &msg) __attribute__((unused))
Support Template for performing a condition test.
DECL_CHECK_OP (eq,==)
Standard Equality Check method.
DECL_CHECK_OP (ne,!=)
Standard Inequality Check method.
DECL_CHECK_OP (ge, >=)
Standard Threshold Check method.
Public Attributes
Suite & ref
Test Suite associated with this Test.
std::string const name
Name of the test case.
int fails
number of FAIL reports for this test.
int skips
number of SKIP reports for this test.
int errors
number of ERROR reports for this test.
std::ostringstream oss
Where to accumulate the output text.
Detailed Description
The Test object.
Derived from Output String Stream.
The Test object constructor writes appropriate opening text to the XML file associatd with the Suite. The destructor writes appropriate text to the XML file to close the XML element corresponding to the test. Methods on Test objects are available for reporting test conditions that are skipped, test conditions that fail, and errors encountered during testing. It is an error to construct a Test object for a Suite that currently has an active Test object. Be sure that each Test object goes out of scope before the next one is constructed.
Data sent to this object using the << operator will be formatted appropriately and displayed by Bamboo as supporting text in appropriate reporting conditions.
Definition at line 38 of file testing_test.hh.
Constructor & Destructor Documentation
Farsyte::Testing::Test::Test (Suite &ref, std::string const &name)
Construct a new Test object.
Parameters:
ref - Suite that contains this Test.
name - what to call this Test. Generates appropriate header text to the XML text output stream to start a new Test. May throw an exception if there is already an existing Test associated with the specified Suite.
Farsyte::Testing::Test::~Test ()
Suite Destructor. Generates an appropriate trailer to the XML text output stream to close the Test. May throw an exception if it appears that this is not the current Test associated with the Suite.
Any text sent to the Test object using the C++ << operator that was not used in a FAIL, SKIP, or ERROR report will be attached to the test as supporting text.
Member Function Documentation
int Farsyte::Testing::Test::check (boolok, std::string const &msg) [inline]
Support code for logging a condition check result.
Parameters:
ok true if the condition passed, false if it failed.
msg message string to associate with the condition
Returns:
zero if the condition passed, nonzero if it failed.
Definition at line 159 of file testing_test.hh.
References fail(), and pass().
Referenced by check_op().
                                                                              {
                if (ok)
                    return pass(msg), 0;
                else
                    return fail(msg), 1;
            }
template<typename T , typename U > int Farsyte::Testing::Test::check_op (T const &ov, U const &ev, boolok, std::string const &op, std::string const &msg) [inline]
Support Template for performing a condition test.
Parameters:
ov observed value
ev expected value
ok result of comparison
op string describing the compare operation
msg string to associate with the condition
Returns:
zero if the condition passed, nonzero if it failed. This template is used if the observed and expected value expressions have different types.
Definition at line 177 of file testing_test.hh.
References check().
                                                               {
                auto w = oss.width();
                oss << std::setw(1);
                oss << "observed: "
                    << std::setw(7) << " " << " "
                    << std::setw((int) w) << ov << std::endl;
                oss << "expected: "
                    << std::setw(7) << op << " "
                    << std::setw((int) w) << ev << std::endl;
                return check(ok, msg);
            }
template<typename T > int Farsyte::Testing::Test::check_op (T const &ov, T const &ev, boolok, std::string const &op, std::string const &msg) [inline]
Support Template for performing a condition test.
Parameters:
ov observed value
ev expected value
ok result of comparison
op string describing the compare operation
msg string to associate with the condition
Returns:
zero if the condition passed, nonzero if it failed. This template is used if the observed and expected value expressions have the same type.
Definition at line 210 of file testing_test.hh.
References check().
                                                               {
                auto w = oss.width();
                oss << std::setw(1);
                oss << "observed: "
                    << std::setw(7) << " " << " "
                    << std::setw((int) w) << ov << std::endl;
                oss << "expected: "
                    << std::setw(7) << op << " "
                    << std::setw((int) w) << ev << std::endl;
                return check(ok, msg);
            }
std::string Farsyte::Testing::Test::drain () [inline]
Get (and clear) accumulated output.
Returns:
a string containing the test output.
Definition at line 61 of file testing_test.hh.
                              {
                std::string s = oss.str();
                oss.str("");
                return s;
            }
void Farsyte::Testing::Test::error (std::string const &cond)
Register a Test ERROR.
Parameters:
cond -- one-line description of the error.
Sends text to the XML log indicating that a test has encountered a testing error, as described in the parameter string. Any accumulated text sent to the Test object with the C++ << operator will be included in the ERROR object as supporting text.
void Farsyte::Testing::Test::fail (std::string const &cond)
Register a Test FAIL.
Parameters:
cond -- one-line description of failed condition.
Sends text to the XML log indicating that a test condition has failed, as described in the parameter string. Any accumulated text sent to the Test object with the C++ << operator will be included in the FAIL object as supporting text.
Referenced by check().
template<typename T > Test& Farsyte::Testing::Test::operator<< (T const &t) [inline]
Append output text.
Parameters:
t value to print to the test log.
Returns:
this test object for further operations.
Definition at line 72 of file testing_test.hh.
                                         {
                oss << t;
                return *this;
            }
Test& Farsyte::Testing::Test::operator<< (std::ostream &(*)(std::ostream &stream)man) [inline]
Apply I/O manipulator.
Parameters:
man manipulator to apply to the log stream.
Returns:
this test object for further operations.
Definition at line 81 of file testing_test.hh.
                                                                     {
                oss << man;
                return *this;
            }
void Farsyte::Testing::Test::pass (std::string const &cond)
Register a Test PASS.
Parameters:
cond -- one-line description of passed condition.
Mark that a test condition has PASSED. There is no XML output for Bamboo in this case. The purpose of this call is to correctly assocaite any supporting text sent to the Test object with this PASSING condition rather than including it in a subsequent fail, skip, or error.
Referenced by check().
void Farsyte::Testing::Test::skip (std::string const &cond)
Register a Test SKIP.
Parameters:
cond -- one-line description of skipped condition.
Sends text to the XML log indicating that a test condition has been skipped, as described in the parameter string. Any accumulated text sent to the Test object with the C++ << operator will be included in the SKIP object as supporting text.
Member Data Documentation
int Farsyte::Testing::Test::errors
number of ERROR reports for this test.
Definition at line 53 of file testing_test.hh.
int Farsyte::Testing::Test::fails
number of FAIL reports for this test.
Definition at line 47 of file testing_test.hh.
std::ostringstream Farsyte::Testing::Test::oss
Where to accumulate the output text.
Definition at line 56 of file testing_test.hh.
Suite& Farsyte::Testing::Test::ref
Test Suite associated with this Test.
Definition at line 41 of file testing_test.hh.
int Farsyte::Testing::Test::skips
number of SKIP reports for this test.
Definition at line 50 of file testing_test.hh.
Author
Generated automatically by Doxygen for The Farsyte Toolkit from the source code.