.TH "Farsyte::Matrix::ThreeVec" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Farsyte::Matrix::ThreeVec \- 
.PP
\fBThreeVec\fP Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix_threevec\&.h>\fP
.PP
Inherits \fBFarsyte::Matrix::ColVec< 3, double >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreeVec\fP ()"
.br
.RI "\fI\fBThreeVec\fP Default Constructor\&. \fP"
.ti -1c
.RI "\fBThreeVec\fP (double x, double y, double z)"
.br
.RI "\fI\fBThreeVec\fP Constructor for Given Coefficients\&. \fP"
.ti -1c
.RI "\fBThreeVec\fP (\fBMatMe\fP const &p)"
.br
.RI "\fIDuplicate Constructor for \fBThreeVec\fP\&. \fP"
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef \fBColVec\fP< 3, double > \fBColMe\fP"
.br
.RI "\fITypedef for \fBColVec\fP generalization\&. \fP"
.ti -1c
.RI "typedef \fBColMe::MatMe\fP \fBMatMe\fP"
.br
.RI "\fITypedef for \fBMatrix\fP generalization\&. \fP"
.ti -1c
.RI "typedef \fBColMe::A\fP \fBA\fP"
.br
.RI "\fITypedef for array containing the data\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBThreeVec\fP Class\&. 

This class implements a representation of a \fBThreeVec\fP (more precisely a change in position), expressed as a column vector of three double precision components\&. 
.PP
Definition at line 22 of file matrix_threevec\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBColMe::MatMe\fP \fBFarsyte::Matrix::ThreeVec::MatMe\fP\fC [protected]\fP"

.PP
Typedef for \fBMatrix\fP generalization\&. 
.PP
Definition at line 29 of file matrix_threevec\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Farsyte::Matrix::ThreeVec::ThreeVec ()"

.PP
\fBThreeVec\fP Default Constructor\&. This class assures that all \fBThreeVec\fP objects are initialized to zero when they are constructed, if no initial value is specified via a different constructor\&. 
.SS "Farsyte::Matrix::ThreeVec::ThreeVec (doublex, doubley, doublez)"

.PP
\fBThreeVec\fP Constructor for Given Coefficients\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP X coefficient for position\&. 
.br
\fIy\fP Y coefficient for position\&. 
.br
\fIz\fP Z coefficient for position\&. Initializes this position to contain the specified coefficients for location along each of the three axes\&. 
.RE
.PP

.SS "Farsyte::Matrix::ThreeVec::ThreeVec (\fBMatMe\fP const &p)"

.PP
Duplicate Constructor for \fBThreeVec\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP \fBThreeVec\fP to duplicate\&. Initializes this position to contain a duplicate of the provided position\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Can be called with any appropriately dimensioned matrix\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
