.TH "Farsyte::Testing::Log" 3 "Sat Sep 27 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Farsyte::Testing::Log \- 
.PP
The \fBLog\fP Object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testing_log\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP (std::ostream &\fBout\fP, std::string const &\fBname\fP)"
.br
.RI "\fI\fBLog\fP Constructor\&. \fP"
.ti -1c
.RI "\fB~Log\fP ()"
.br
.RI "\fI\fBLog\fP Destructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::ostream & \fBout\fP"
.br
.RI "\fICurrent output stream\&. \fP"
.ti -1c
.RI "std::string const \fBname\fP"
.br
.RI "\fIName of the test log\&. \fP"
.ti -1c
.RI "\fBSuite\fP * \fBcurr\fP"
.br
.RI "\fICurrently active \fBSuite\fP, or NULL if none\&. \fP"
.ti -1c
.RI "int \fBsuites\fP"
.br
.RI "\fICumulative count of Suites\&. \fP"
.ti -1c
.RI "int \fBtests\fP"
.br
.RI "\fICumulative count of Tests\&. \fP"
.ti -1c
.RI "int \fBfailed_tests\fP"
.br
.RI "\fICumulative count of Tests with at least one FAIL\&. \fP"
.ti -1c
.RI "int \fBskipped_tests\fP"
.br
.RI "\fICumulative count of Tests with at least one SKIP\&. \fP"
.ti -1c
.RI "int \fBerrored_tests\fP"
.br
.RI "\fICumulative count of Tests with at least one ERROR\&. \fP"
.ti -1c
.RI "int \fBtotal_fails\fP"
.br
.RI "\fICumulative count of all FAIL reports\&. \fP"
.ti -1c
.RI "int \fBtotal_skips\fP"
.br
.RI "\fICumulative count of all SKIP reports\&. \fP"
.ti -1c
.RI "int \fBtotal_errors\fP"
.br
.RI "\fICumulative count of all ERROR reports\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBLog\fP Object\&. 

The \fBLog\fP object constructor writes XML text to the specified output stream to start a new log file\&. The destructor writes trailer data to finish the XML element opened at the top\&. \fBTest\fP programs create a \fBLog\fP object for each file they want to write, and may have several \fBLog\fP file objects open at the same time\&. 
.PP
Definition at line 24 of file testing_log\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Farsyte::Testing::Log::Log (std::ostream &out, std::string const &name)"

.PP
\fBLog\fP Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIout\fP - where to send the XML text\&. 
.br
\fIname\fP - the name of the \fBLog\fP\&. Writes XML header text to the output stream\&. 
.RE
.PP

.SS "Farsyte::Testing::Log::~Log ()"

.PP
\fBLog\fP Destructor\&. Writes XML trailer text to the output stream\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
