.TH "Farsyte::Matrix::ColVec< Nr, T >" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Farsyte::Matrix::ColVec< Nr, T > \- 
.PP
Column Vector Template\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix_colvec\&.h>\fP
.PP
Inherits \fBFarsyte::Matrix::Matrix< 1, Nr, T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBMatrix\fP< 1, Nr, T > \fBMatMe\fP"
.br
.RI "\fITypedef for matrix generalization\&. \fP"
.ti -1c
.RI "typedef \fBMatMe::A\fP \fBA\fP"
.br
.RI "\fITypedef for array containing the data\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColVec\fP (\fBA\fP const &\fBa\fP)"
.br
.RI "\fIConstruct a Column Vector from a 2-D Array\&. \fP"
.ti -1c
.RI "\fBColVec\fP (\fBMatMe\fP const &c)"
.br
.RI "\fIDuplicate an existing Column Vector\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<int Nr, typename T>class Farsyte::Matrix::ColVec< Nr, T >"
Column Vector Template\&. 


.PP
\fBParameters:\fP
.RS 4
\fINr\fP Number of rows in the vector\&. 
.br
\fIT\fP Data type for each vector element\&.
.RE
.PP
This template implements a column vector of a compile-time determined size, containing elements of compile-time determined type\&. 
.PP
Definition at line 25 of file matrix_colvec\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<int Nr, typename T> typedef \fBMatrix\fP<1, Nr, T> \fBFarsyte::Matrix::ColVec\fP< Nr, T >::\fBMatMe\fP"

.PP
Typedef for matrix generalization\&. 
.PP
Definition at line 31 of file matrix_colvec\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int Nr, typename T> \fBFarsyte::Matrix::ColVec\fP< Nr, T >::\fBColVec\fP (\fBA\fP const &a)\fC [inline]\fP"

.PP
Construct a Column Vector from a 2-D Array\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP An appropriately shaped object of the C++ array template type\&. This initializes the Column Vector data to contain values from the corresponding elements of the array provided\&. 
.RE
.PP

.PP
Definition at line 48 of file matrix_colvec\&.h\&.
.PP
.nf
49                     : MatMe(a) {
50             }
.fi
.SS "template<int Nr, typename T> \fBFarsyte::Matrix::ColVec\fP< Nr, T >::\fBColVec\fP (\fBMatMe\fP const &c)\fC [inline]\fP"

.PP
Duplicate an existing Column Vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP A column vector to duplicate\&. Initialize this column vector to be a duplicate of the one provided\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Can be called with any appropriately dimensioned matrix\&. 
.RE
.PP

.PP
Definition at line 57 of file matrix_colvec\&.h\&.
.PP
.nf
58                     : MatMe(c) {
59             }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
