.TH "matrix_threevec.h" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix_threevec.h \- 
.PP
Matrix Library Exported API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'matrix_colvec\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFarsyte::Matrix::ThreeVec\fP"
.br
.RI "\fI\fBThreeVec\fP Class\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_matrix_threevec_h\fP   'matrix threevec v0\&.1'"
.br
.RI "\fIfor header vs library matching \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ThreeVec \fBFarsyte::Matrix::cross\fP (Matrix< 1, 3, double > const &L, Matrix< 1, 3, double > const &R)"
.br
.RI "\fICross-Product operation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Matrix Library Exported API\&. 

This file provides data types, function prototypes and macro definitions for C code using this Matrix library\&. 
.PP
Definition in file \fBmatrix_threevec\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
