.TH "testing_oops.h" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing_oops.h \- 
.PP
Testing Oops Interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFarsyte::Testing::Oops\fP"
.br
.RI "\fIThe \fBOops\fP Object\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_testing_oops_h\fP   'testing oops v0\&.1'"
.br
.RI "\fIfor header vs library matching \fP"
.in -1c
.SH "Detailed Description"
.PP 
Testing Oops Interface\&. 


.IP "\(bu" 2

.PP

.PP
Definition in file \fBtesting_oops\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
