.TH "testing.h" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing.h \- 
.PP
Testing Library Exported API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'testing_log\&.h'\fP
.br
\fC#include 'testing_suite\&.h'\fP
.br
\fC#include 'testing_test\&.h'\fP
.br
\fC#include 'testing_oops\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_testing_h\fP   'testing v0\&.1'"
.br
.RI "\fIfor header vs library matching \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< std::string > const & \fBFarsyte::Testing::testing_versions\fP ()"
.br
.RI "\fIRetrieve 'testing' version strings from library\&. \fP"
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &s, \fBFarsyte::Testing::Oops\fP const &f)"
.br
.RI "\fIDump information from an Oops onto an output stream\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Testing Library Exported API\&. 

This file provides data types, function prototypes and macro definitions for C code using this Testing library\&. 
.PP
Definition in file \fBtesting\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
