.TH "testing.h" 3 "Mon Sep 15 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing.h \- 
.PP
Testing Library Exported API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFarsyte::Testing::Log\fP"
.br
.RI "\fIThe \fBLog\fP Object\&. \fP"
.ti -1c
.RI "class \fBFarsyte::Testing::Suite\fP"
.br
.RI "\fIThe \fBSuite\fP Object\&. \fP"
.ti -1c
.RI "class \fBFarsyte::Testing::Test\fP"
.br
.RI "\fIThe \fBTest\fP object\&. \fP"
.ti -1c
.RI "class \fBFarsyte::Testing::Oops\fP"
.br
.RI "\fIThe \fBOops\fP Object\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &s, \fBFarsyte::Testing::Oops\fP const &f)"
.br
.RI "\fIDump information from an Oops onto an output stream\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Testing Library Exported API\&. 

This file provides data types, function prototypes and macro definitions for C code using this Testing library\&. 
.PP
Definition in file \fBtesting\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
