.TH "testing_test.h" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing_test.h \- 
.PP
Testing Test Case Interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFarsyte::Testing::Test\fP"
.br
.RI "\fIThe \fBTest\fP object\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_testing_test_h\fP   'testing test v0\&.1'"
.br
.RI "\fIfor header vs library matching \fP"
.in -1c
.SH "Detailed Description"
.PP 
Testing Test Case Interface\&. 


.IP "\(bu" 2

.PP

.PP
Definition in file \fBtesting_test\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
