.TH "utility.h" 3 "Mon Sep 22 2014" "The Farsyte Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility.h \- 
.PP
Testing Library Exported API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_utility_h\fP   'utility v0\&.1'"
.br
.RI "\fIfor header vs library matching \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBFarsyte::Utility::literal\fP (char ch)"
.br
.RI "\fIConvert a character into its literal representation\&. \fP"
.ti -1c
.RI "std::string \fBFarsyte::Utility::literal\fP (std::string const &str)"
.br
.RI "\fIConvert a string into its literal representation (without quotes)\&. \fP"
.ti -1c
.RI "std::string \fBFarsyte::Utility::quoted\fP (std::string const &str)"
.br
.RI "\fIConvert a character into its literal representation (with quotes)\&. \fP"
.ti -1c
.RI "std::string \fBFarsyte::Utility::htmlify\fP (char ch)"
.br
.RI "\fIConvert a character into its HTML representation\&. \fP"
.ti -1c
.RI "std::string \fBFarsyte::Utility::htmlify\fP (std::string const &str)"
.br
.RI "\fIConvert a string into its HTML representation\&. \fP"
.ti -1c
.RI "std::vector< std::string > \fBFarsyte::Utility::streamlines\fP (std::ostringstream &oss)"
.br
.RI "\fIGiven an output string stream, extract its content as one string per line into a vector of strings\&. \fP"
.ti -1c
.RI "std::vector< std::string > const & \fBFarsyte::Utility::utility_versions\fP ()"
.br
.RI "\fIRetrieve 'utility' version strings from library\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Testing Library Exported API\&. 

This file provides data types, function prototypes and macro definitions for C code using this Testing library\&. 
.PP
Definition in file \fButility\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for The Farsyte Toolkit from the source code\&.
